language: python

before_install:
  - sudo apt-get update

install:
  - wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.10.1-1-amd64.deb
  - sudo apt-get install -y texlive-generic-recommended texlive-xetex lmodern texlive-fonts-recommended
  - sudo apt-get install -y poppler-utils
  - sudo apt-get install -y libimage-exiftool-perl
  - if [ ! -d ~/.fonts/ ]; then mkdir -p ~/.fonts && wget https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip && unzip Noto-hinted.zip -d ~/.fonts/; fi
  - fc-cache -f -v
  - git clone https://github.com/ioi-2017/tps.git
  - cd tps
  - sudo ./install-tps.sh
script:
  - cd ..
  - make statement
  - make merge-pdf
  - mkdir -p statement
  - cp pA/statement/index.pdf statement/pA.pdf
  - cp pB/statement/index.pdf statement/pB.pdf
  - cp pC/statement/index.pdf statement/pC.pdf
  - cp pD/statement/index.pdf statement/pD.pdf
  - cp pE/statement/index.pdf statement/pE.pdf
  - cp pA/attachments/problems.pdf statement/problems.pdf
cache:
  directories:
    - ~/.fonts/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: statement/*
  skip_cleanup: true
  draft: true
  overwrite: true
