language: python

before_install:
  - sudo apt-get update

install:
  - wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.10.1-1-amd64.deb
  - sudo apt-get install -y texlive-generic-recommended texlive-xetex lmodern
  - sudo apt-get install -y poppler-utils
  - wget https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip
  - mkdir -p ~/.fonts
  - unzip Noto-hinted.zip -d ~/.fonts/
  - fc-cache -f -v 
  - git clone https://github.com/ioi-2017/tps.git
  - cd tps
  - sudo ./install-tps.sh
script:
  - cd ..
  - cd pA
  - tps statement
